/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdad3",
        "tertiary": "#120000",
        "on-secondary-fixed-variant": "#254f3b",
        "surface-tint": "#5d5e62",
        "on-primary-container": "#848689",
        "sage-forest": "#2B5440",
        "surface-dim": "#dbdad6",
        "cardstock": "#FFFFFF",
        "surface-container": "#efeeea",
        "inverse-primary": "#c6c6ca",
        "outline-variant": "#c6c6ca",
        "outline": "#76777b",
        "slate": "#686E78",
        "primary-fixed": "#e2e2e6",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c6c6ca",
        "on-tertiary-fixed-variant": "#7d2c1e",
        "on-primary-fixed": "#1a1c1f",
        "surface-variant": "#e3e2df",
        "on-surface-variant": "#45474a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f4f0",
        "on-tertiary-fixed": "#3f0300",
        "secondary-fixed": "#bfedd2",
        "secondary-container": "#bfedd2",
        "on-tertiary-container": "#cd6956",
        "inverse-on-surface": "#f2f1ed",
        "secondary": "#3e6752",
        "on-error": "#ffffff",
        "primary-container": "#1c1e21",
        "on-secondary": "#ffffff",
        "tertiary-container": "#440300",
        "on-primary": "#ffffff",
        "primary": "#030406",
        "on-background": "#1b1c1a",
        "surface-container-highest": "#e3e2df",
        "secondary-fixed-dim": "#a4d1b7",
        "error-container": "#ffdad6",
        "paper-hairline": "rgba(28, 30, 33, 0.12)",
        "muted-terracotta": "#9E4535",
        "on-secondary-container": "#436d57",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a6",
        "on-primary-fixed-variant": "#45474a",
        "surface-container-high": "#e9e8e4",
        "background": "#faf9f5",
        "on-secondary-fixed": "#002113",
        "surface": "#faf9f5",
        "on-surface": "#1b1c1a",
        "surface-bright": "#faf9f5",
        "inverse-surface": "#30312e",
        "error": "#ba1a1a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "ledger-num": ["JetBrains Mono", "monospace"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "ledger-num-lg": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.15", letterSpacing: "-0.03em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "ledger-num": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "ledger-num-lg": ["20px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
